require_relative '../node_modules/react-native/scripts/react_native_pods'

# Enable modular headers to allow Swift pods (FirebaseCoreInternal) to be imported when using static libraries
use_modular_headers!

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MirrorCollectiveApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Firebase pods (added for App + App Distribution)
  pod 'Firebase/Core'
  pod 'FirebaseAppDistribution'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
