/**
 * Toast — minimal in-app banner notification.
 *
 * Replaces `Alert.alert` for transient feedback (purchase succeeded,
 * restored, etc.). Alerts are blocking and feel heavy in a real-money
 * flow; a top-anchored banner that auto-dismisses is the standard
 * subscription-app pattern.
 *
 * Why in-house instead of a library:
 *   - Zero new dependencies.
 *   - Tight palette match to the rest of the app (Cormorant heading +
 *     gold accents on the gold-bordered navy card).
 *   - Renders under 100 lines including styles.
 *
 * Public API lives in `useToast` (ToastContext.tsx); this file is the
 * presentational component only.
 */

import LinearGradient from 'react-native-linear-gradient';
import React, { useEffect, useMemo, useRef } from 'react';
import {
  Animated,
  Pressable,
  StyleSheet,
  Text,
  type TextStyle,
  type ViewStyle,
} from 'react-native';

import {
  borderWidth,
  fontFamily,
  fontSize,
  fontWeight,
  modalColors,
  moderateScale,
  palette,
  radius,
  scale,
  spacing,
  verticalScale,
} from '@theme';

export type ToastTone = 'info' | 'success' | 'error';

export interface ToastSpec {
  /** Stable id, generated by the provider. */
  id: number;
  message: string;
  tone?: ToastTone;
  /** Optional bold title shown above the message. */
  title?: string;
}

interface ToastProps {
  spec: ToastSpec;
  /** Called when the auto-dismiss timer fires or the user taps the toast. */
  onDismiss: (id: number) => void;
  /** Total time the toast stays visible, including the fade-out. */
  durationMs?: number;
}

const FADE_MS = 220;

const Toast: React.FC<ToastProps> = ({ spec, onDismiss, durationMs = 3200 }) => {
  const opacity = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    // Fade in, hold, fade out, then notify the provider so it removes
    // the spec from the queue.
    //
    // Dismissal timing is driven by two setTimeouts (NOT by the
    // Animated.timing completion callback). Under jest fake timers
    // Animated doesn't advance, so anchoring the timer to setTimeout
    // keeps the unit-test behaviour predictable. The fade is purely
    // decorative and visually completes before the dismissal anyway.
    Animated.timing(opacity, {
      toValue: 1,
      duration: FADE_MS,
      useNativeDriver: true,
    }).start();

    const fadeOutTimer = setTimeout(() => {
      Animated.timing(opacity, {
        toValue: 0,
        duration: FADE_MS,
        useNativeDriver: true,
      }).start();
    }, durationMs - FADE_MS);
    const dismissTimer = setTimeout(() => {
      onDismiss(spec.id);
    }, durationMs);

    return () => {
      clearTimeout(fadeOutTimer);
      clearTimeout(dismissTimer);
    };
    // Spec id is stable; nothing else changes after mount.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [spec.id]);

  const toneStyle = useMemo(() => toneStyles[spec.tone ?? 'info'], [spec.tone]);

  return (
    <Animated.View
      accessibilityLiveRegion="polite"
      accessibilityRole="alert"
      style={[styles.wrapper, { opacity }]}
      pointerEvents="box-none"
    >
      <Pressable
        accessibilityRole="button"
        accessibilityLabel={spec.title ? `${spec.title}. ${spec.message}` : spec.message}
        onPress={() => onDismiss(spec.id)}
      >
        <LinearGradient
          colors={[
            'rgba(155, 170, 194, 0.05)',
            'rgba(155, 170, 194, 0.22)',
          ]}
          start={{ x: 0.5, y: 0 }}
          end={{ x: 0.5, y: 1 }}
          style={[styles.card, toneStyle.border]}
        >
          {spec.title ? (
            <Text style={[styles.title, toneStyle.text]} numberOfLines={1}>
              {spec.title}
            </Text>
          ) : null}
          <Text style={[styles.message, toneStyle.text]} numberOfLines={3}>
            {spec.message}
          </Text>
        </LinearGradient>
      </Pressable>
    </Animated.View>
  );
};

export default Toast;

const styles = StyleSheet.create<{
  wrapper: ViewStyle;
  card: ViewStyle;
  title: TextStyle;
  message: TextStyle;
}>({
  wrapper: {
    paddingHorizontal: scale(spacing.l),
    paddingVertical: verticalScale(spacing.xs),
  },
  card: {
    paddingVertical: verticalScale(spacing.m),
    paddingHorizontal: scale(spacing.l),
    borderRadius: radius.m,
    borderWidth: borderWidth.thin,
    shadowColor: modalColors.textGoldMuted,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 14,
    elevation: 8,
  },
  title: {
    fontFamily: fontFamily.heading,
    fontSize: moderateScale(fontSize.l),
    fontWeight: fontWeight.regular,
    lineHeight: moderateScale(fontSize.l) * 1.2,
    marginBottom: verticalScale(spacing.xs),
  },
  message: {
    fontFamily: fontFamily.body,
    fontSize: moderateScale(fontSize.s),
    fontWeight: fontWeight.light,
    lineHeight: moderateScale(fontSize.s) * 1.4,
  },
});

interface ToneStyle {
  border: ViewStyle;
  text: TextStyle;
}

const toneStyles: Record<ToastTone, ToneStyle> = {
  info: {
    border: { borderColor: palette.navy.light },
    text: { color: palette.gold.subtlest },
  },
  success: {
    border: { borderColor: palette.gold.DEFAULT },
    text: { color: palette.gold.DEFAULT },
  },
  error: {
    border: { borderColor: palette.status.errorHover },
    text: { color: palette.status.errorHover },
  },
};
